# =============================================================================
# 04_GSEA.R
#
# TFM: Transcriptomic response of human induced neurons to ionizing radiation
#
# Purpose:
#   Preranked Gene Set Enrichment Analysis (GSEA) using the moderated
#   t-statistic generated by 03_differential_expression.R.
#
# Collections:
#   1. MSigDB Hallmark
#   2. Gene Ontology Biological Process (GO:BP)
#   3. KEGG Legacy
#
# Ranking:
#   Unique gene symbols ranked by moderated t-statistic.
#
# Interpretation:
#   Positive NES = enrichment towards IR
#   Negative NES = enrichment towards CTL
#
# Reproducibility environment validated during TFM reconstruction:
#   MSigDB: 2026.1.Hs
#   msigdbr: 26.1.1
#   fgsea: 1.38.0
# =============================================================================


# =============================================================================
# 1. REQUIRED PACKAGES
# =============================================================================

required <- c(
    "fgsea",
    "msigdbr",
    "ggplot2"
)

missing_packages <- required[
    !vapply(
        required,
        requireNamespace,
        logical(1),
        quietly = TRUE
    )
]

if (length(missing_packages) > 0L) {
    stop(
        "Install missing packages before running this script: ",
        paste(missing_packages, collapse = ", ")
    )
}

library(fgsea)
library(msigdbr)
library(ggplot2)


# =============================================================================
# 2. OUTPUT DIRECTORIES
# =============================================================================

dir.create(
    "results/GSEA",
    recursive = TRUE,
    showWarnings = FALSE
)

dir.create(
    "figures/GSEA",
    recursive = TRUE,
    showWarnings = FALSE
)


# =============================================================================
# 3. LOAD GSEA RANKING GENERATED BY 03_differential_expression.R
# =============================================================================

ranking_file <- "results/GSEA_ranked_genes.csv"

if (!file.exists(ranking_file)) {
    stop(
        "Cannot find ",
        ranking_file,
        ". Run 03_differential_expression.R first."
    )
}

ranking_df <- read.csv(
    ranking_file,
    stringsAsFactors = FALSE,
    check.names = FALSE
)

required_columns <- c(
    "gene_symbol",
    "t"
)

if (!all(required_columns %in% names(ranking_df))) {
    stop(
        "GSEA ranking must contain columns: ",
        paste(required_columns, collapse = ", ")
    )
}


# =============================================================================
# 4. BUILD GSEA RANKING
# =============================================================================

ranking_df <- ranking_df[
    !is.na(ranking_df$gene_symbol) &
    ranking_df$gene_symbol != "" &
    !is.na(ranking_df$t) &
    is.finite(ranking_df$t),
    ,
    drop = FALSE
]

# If duplicated symbols are present, retain the observation with the
# largest absolute moderated t-statistic.

ranking_df <- ranking_df[
    order(
        abs(ranking_df$t),
        decreasing = TRUE
    ),
    ,
    drop = FALSE
]

ranking_df <- ranking_df[
    !duplicated(ranking_df$gene_symbol),
    ,
    drop = FALSE
]

ranks <- ranking_df$t

names(ranks) <- ranking_df$gene_symbol

ranks <- sort(
    ranks,
    decreasing = TRUE
)

if (anyDuplicated(names(ranks))) {
    stop(
        "Duplicated gene symbols remain in the GSEA ranking."
    )
}

if (anyNA(ranks)) {
    stop(
        "NA values remain in the GSEA ranking."
    )
}

cat("\n")
cat("============================================================\n")
cat("GSEA INPUT\n")
cat("============================================================\n\n")

cat(
    "Genes in ranked list:",
    length(ranks),
    "\n"
)

cat(
    sprintf(
        "t-statistic range: %.3f to %.3f\n",
        min(ranks),
        max(ranks)
    )
)

if (length(ranks) != 17919L) {
    warning(
        "Expected 17,919 ranked genes, but found ",
        length(ranks),
        "."
    )
}


# =============================================================================
# 5. DOWNLOAD MSigDB COLLECTIONS
# =============================================================================

cat("\nLoading MSigDB Hallmark...\n")

hallmark_msig <- msigdbr(
    species = "Homo sapiens",
    collection = "H"
)

cat("Loading MSigDB GO:BP...\n")

gobp_msig <- msigdbr(
    species = "Homo sapiens",
    collection = "C5",
    subcollection = "GO:BP"
)

cat("Loading MSigDB KEGG Legacy...\n")

kegg_msig <- msigdbr(
    species = "Homo sapiens",
    collection = "C2",
    subcollection = "CP:KEGG_LEGACY"
)


# =============================================================================
# 6. CHECK MSigDB VERSION
# =============================================================================

msigdb_versions <- unique(
    c(
        hallmark_msig$db_version,
        gobp_msig$db_version,
        kegg_msig$db_version
    )
)

cat(
    "\nMSigDB version:",
    paste(msigdb_versions, collapse = ", "),
    "\n"
)

cat(
    "msigdbr version:",
    as.character(packageVersion("msigdbr")),
    "\n"
)

cat(
    "fgsea version:",
    as.character(packageVersion("fgsea")),
    "\n"
)

if (length(msigdb_versions) != 1L) {
    warning(
        "Different MSigDB versions detected between collections."
    )
}


# =============================================================================
# 7. BUILD PATHWAY LISTS
# =============================================================================

make_pathway_list <- function(msig_df) {

    if (!all(
        c(
            "gs_name",
            "gene_symbol"
        ) %in% names(msig_df)
    )) {
        stop(
            "MSigDB table does not contain gs_name and gene_symbol."
        )
    }

    pathways <- split(
        msig_df$gene_symbol,
        msig_df$gs_name
    )

    pathways <- lapply(
        pathways,
        function(x) {

            x <- x[
                !is.na(x) &
                x != ""
            ]

            unique(x)
        }
    )

    pathways
}


hallmark_pathways <- make_pathway_list(
    hallmark_msig
)

gobp_pathways <- make_pathway_list(
    gobp_msig
)

kegg_pathways <- make_pathway_list(
    kegg_msig
)


cat("\n")
cat("Available gene sets before GSEA filtering:\n")

cat(
    "  Hallmark:",
    length(hallmark_pathways),
    "\n"
)

cat(
    "  GO:BP:",
    length(gobp_pathways),
    "\n"
)

cat(
    "  KEGG Legacy:",
    length(kegg_pathways),
    "\n"
)


# =============================================================================
# 8. GSEA FUNCTION
# =============================================================================
#
# fgsea applies minSize and maxSize after matching pathway genes against
# the genes present in the ranked list.
#
# No additional manual size prefiltering is performed here.
# =============================================================================

run_gsea <- function(pathways, stats) {

    set.seed(123)

    result <- fgseaMultilevel(
        pathways = pathways,
        stats = stats,
        minSize = 15,
        maxSize = 500,
        eps = 0
    )

    result <- as.data.frame(result)

    result <- result[
        order(
            result$padj,
            -abs(result$NES)
        ),
        ,
        drop = FALSE
    ]

    result$direction <- ifelse(
        result$NES > 0,
        "IR",
        "CTL"
    )

    rownames(result) <- NULL

    result
}


# =============================================================================
# 9. RUN HALLMARK GSEA
# =============================================================================

cat("\n")
cat("============================================================\n")
cat("HALLMARK GSEA\n")
cat("============================================================\n\n")

hallmark_gsea <- run_gsea(
    hallmark_pathways,
    ranks
)

hallmark_sig <- hallmark_gsea[
    !is.na(hallmark_gsea$padj) &
    hallmark_gsea$padj < 0.05,
    ,
    drop = FALSE
]

cat(
    "Hallmark pathways tested:",
    nrow(hallmark_gsea),
    "\n"
)

cat(
    "Hallmark significant (FDR < 0.05):",
    nrow(hallmark_sig),
    "\n"
)

cat(
    "Positive NES / IR:",
    sum(hallmark_sig$NES > 0),
    "\n"
)

cat(
    "Negative NES / CTL:",
    sum(hallmark_sig$NES < 0),
    "\n"
)


# =============================================================================
# 10. RUN GO:BP GSEA
# =============================================================================

cat("\n")
cat("============================================================\n")
cat("GO BIOLOGICAL PROCESS GSEA\n")
cat("============================================================\n\n")

gobp_gsea <- run_gsea(
    gobp_pathways,
    ranks
)

gobp_sig <- gobp_gsea[
    !is.na(gobp_gsea$padj) &
    gobp_gsea$padj < 0.05,
    ,
    drop = FALSE
]

gobp_positive <- gobp_sig[
    gobp_sig$NES > 0,
    ,
    drop = FALSE
]

gobp_negative <- gobp_sig[
    gobp_sig$NES < 0,
    ,
    drop = FALSE
]

cat(
    "GO:BP terms tested:",
    nrow(gobp_gsea),
    "\n"
)

cat(
    "GO:BP significant:",
    nrow(gobp_sig),
    "\n"
)

cat(
    "Positive NES / IR:",
    nrow(gobp_positive),
    "\n"
)

cat(
    "Negative NES / CTL:",
    nrow(gobp_negative),
    "\n"
)


# =============================================================================
# 11. RUN KEGG LEGACY GSEA
# =============================================================================

cat("\n")
cat("============================================================\n")
cat("KEGG LEGACY GSEA\n")
cat("============================================================\n\n")

kegg_gsea <- run_gsea(
    kegg_pathways,
    ranks
)

kegg_sig <- kegg_gsea[
    !is.na(kegg_gsea$padj) &
    kegg_gsea$padj < 0.05,
    ,
    drop = FALSE
]

kegg_positive <- kegg_sig[
    kegg_sig$NES > 0,
    ,
    drop = FALSE
]

kegg_negative <- kegg_sig[
    kegg_sig$NES < 0,
    ,
    drop = FALSE
]

cat(
    "KEGG pathways tested:",
    nrow(kegg_gsea),
    "\n"
)

cat(
    "KEGG significant:",
    nrow(kegg_sig),
    "\n"
)

cat(
    "Positive NES / IR:",
    nrow(kegg_positive),
    "\n"
)

cat(
    "Negative NES / CTL:",
    nrow(kegg_negative),
    "\n"
)


# =============================================================================
# 12. SAFE CSV EXPORT FUNCTION
# =============================================================================
#
# fgsea returns leadingEdge as a list-column.
# write.csv() cannot write list-columns directly.
#
# Therefore, leadingEdge is converted to a semicolon-separated string
# only in the copy used for CSV export.
#
# The original GSEA objects retain the list-column for downstream analysis.
# =============================================================================

prepare_gsea_for_csv <- function(x) {

    out <- as.data.frame(x)

    if ("leadingEdge" %in% names(out)) {

        out$leadingEdge <- vapply(
            out$leadingEdge,
            function(z) {

                paste(
                    z,
                    collapse = ";"
                )
            },
            character(1)
        )
    }

    out
}


# =============================================================================
# 13. EXPORT COMPLETE GSEA RESULTS
# =============================================================================

write.csv(
    prepare_gsea_for_csv(hallmark_gsea),
    "results/GSEA/Hallmark_GSEA_all.csv",
    row.names = FALSE
)

write.csv(
    prepare_gsea_for_csv(hallmark_sig),
    "results/GSEA/Hallmark_GSEA_significant.csv",
    row.names = FALSE
)


write.csv(
    prepare_gsea_for_csv(gobp_gsea),
    "results/GSEA/GO_BP_GSEA_all.csv",
    row.names = FALSE
)

write.csv(
    prepare_gsea_for_csv(gobp_sig),
    "results/GSEA/GO_BP_GSEA_significant.csv",
    row.names = FALSE
)

write.csv(
    prepare_gsea_for_csv(gobp_positive),
    "results/GSEA/GO_BP_positive_IR.csv",
    row.names = FALSE
)

write.csv(
    prepare_gsea_for_csv(gobp_negative),
    "results/GSEA/GO_BP_negative_CTL.csv",
    row.names = FALSE
)


write.csv(
    prepare_gsea_for_csv(kegg_gsea),
    "results/GSEA/KEGG_Legacy_GSEA_all.csv",
    row.names = FALSE
)

write.csv(
    prepare_gsea_for_csv(kegg_sig),
    "results/GSEA/KEGG_Legacy_GSEA_significant.csv",
    row.names = FALSE
)

write.csv(
    prepare_gsea_for_csv(kegg_positive),
    "results/GSEA/KEGG_Legacy_positive_IR.csv",
    row.names = FALSE
)

write.csv(
    prepare_gsea_for_csv(kegg_negative),
    "results/GSEA/KEGG_Legacy_negative_CTL.csv",
    row.names = FALSE
)


# =============================================================================
# 14. SELECT HALLMARK PATHWAYS OF BIOLOGICAL INTEREST
# =============================================================================

hallmark_targets <- c(
    "HALLMARK_P53_PATHWAY",
    "HALLMARK_OXIDATIVE_PHOSPHORYLATION",
    "HALLMARK_TNFA_SIGNALING_VIA_NFKB",
    "HALLMARK_APOPTOSIS",
    "HALLMARK_DNA_REPAIR",
    "HALLMARK_G2M_CHECKPOINT"
)

hallmark_interest <- hallmark_gsea[
    hallmark_gsea$pathway %in% hallmark_targets,
    ,
    drop = FALSE
]

hallmark_interest$order_id <- match(
    hallmark_interest$pathway,
    hallmark_targets
)

hallmark_interest <- hallmark_interest[
    order(hallmark_interest$order_id),
    ,
    drop = FALSE
]

hallmark_interest$order_id <- NULL


write.csv(
    prepare_gsea_for_csv(hallmark_interest),
    "results/GSEA/Hallmark_selected_pathways.csv",
    row.names = FALSE
)


# =============================================================================
# 15. LEADING-EDGE ANALYSIS
# =============================================================================

hallmark_leading_edge_table <- data.frame(
    pathway = hallmark_interest$pathway,
    size = hallmark_interest$size,
    ES = hallmark_interest$ES,
    NES = hallmark_interest$NES,
    padj = hallmark_interest$padj,

    leading_edge_n = lengths(
        hallmark_interest$leadingEdge
    ),

    leading_edge_genes = vapply(
        hallmark_interest$leadingEdge,
        function(x) {

            paste(
                x,
                collapse = ";"
            )
        },
        character(1)
    ),

    stringsAsFactors = FALSE
)


write.csv(
    hallmark_leading_edge_table,
    "results/GSEA/Hallmark_leading_edges.csv",
    row.names = FALSE
)


# =============================================================================
# 16. LEADING-EDGE OVERLAP
# =============================================================================

get_leading_edge <- function(pathway_name) {

    idx <- which(
        hallmark_interest$pathway ==
            pathway_name
    )

    if (length(idx) != 1L) {
        return(character(0))
    }

    hallmark_interest$leadingEdge[[idx]]
}


p53_le <- get_leading_edge(
    "HALLMARK_P53_PATHWAY"
)

dna_repair_le <- get_leading_edge(
    "HALLMARK_DNA_REPAIR"
)

apoptosis_le <- get_leading_edge(
    "HALLMARK_APOPTOSIS"
)

tnfa_le <- get_leading_edge(
    "HALLMARK_TNFA_SIGNALING_VIA_NFKB"
)


leading_edge_overlap <- data.frame(

    comparison = c(
        "P53 vs DNA repair",
        "P53 vs apoptosis",
        "P53 vs TNFA/NFKB"
    ),

    shared_genes_n = c(
        length(
            intersect(
                p53_le,
                dna_repair_le
            )
        ),

        length(
            intersect(
                p53_le,
                apoptosis_le
            )
        ),

        length(
            intersect(
                p53_le,
                tnfa_le
            )
        )
    ),

    shared_genes = c(

        paste(
            intersect(
                p53_le,
                dna_repair_le
            ),
            collapse = ";"
        ),

        paste(
            intersect(
                p53_le,
                apoptosis_le
            ),
            collapse = ";"
        ),

        paste(
            intersect(
                p53_le,
                tnfa_le
            ),
            collapse = ";"
        )
    ),

    stringsAsFactors = FALSE
)


write.csv(
    leading_edge_overlap,
    "results/GSEA/Hallmark_leading_edge_overlap.csv",
    row.names = FALSE
)


# =============================================================================
# 17. HALLMARK FIGURE
# =============================================================================

plot_df <- hallmark_interest

plot_df$label <- gsub(
    "^HALLMARK_",
    "",
    plot_df$pathway
)

plot_df$label <- gsub(
    "_",
    " ",
    plot_df$label
)

plot_df$label <- factor(
    plot_df$label,
    levels = rev(plot_df$label)
)


p_hallmark <- ggplot(
    plot_df,
    aes(
        x = NES,
        y = label,
        fill = direction
    )
) +

    geom_col(
        width = 0.75
    ) +

    geom_vline(
        xintercept = 0,
        linewidth = 0.4
    ) +

    labs(
        title = "Selected Hallmark pathways",
        subtitle = "Positive NES: IR | Negative NES: CTL",
        x = "Normalized Enrichment Score (NES)",
        y = NULL,
        fill = "Enriched toward"
    ) +

    theme_classic(
        base_size = 12
    )


ggsave(
    "figures/GSEA/Hallmark_selected_NES.pdf",
    p_hallmark,
    width = 8,
    height = 5
)

ggsave(
    "figures/GSEA/Hallmark_selected_NES.png",
    p_hallmark,
    width = 8,
    height = 5,
    dpi = 300
)


# =============================================================================
# 18. P53 ENRICHMENT CURVE
# =============================================================================

p53_name <- "HALLMARK_P53_PATHWAY"

if (p53_name %in% names(hallmark_pathways)) {

    p_p53 <- plotEnrichment(
        hallmark_pathways[[p53_name]],
        ranks
    ) +

        labs(
            title = "GSEA enrichment plot: p53 pathway",
            subtitle = "IR vs CTL"
        ) +

        theme_classic(
            base_size = 12
        )


    ggsave(
        "figures/GSEA/Hallmark_P53_enrichment.pdf",
        p_p53,
        width = 8,
        height = 5
    )

    ggsave(
        "figures/GSEA/Hallmark_P53_enrichment.png",
        p_p53,
        width = 8,
        height = 5,
        dpi = 300
    )
}



# =============================================================================
# 18B. DNA REPAIR ENRICHMENT CURVE
# =============================================================================

dna_repair_name <- "HALLMARK_DNA_REPAIR"

if (dna_repair_name %in% names(hallmark_pathways)) {

    dna_repair_result <- hallmark_gsea[
        hallmark_gsea$pathway == dna_repair_name,
        ,
        drop = FALSE
    ]

    p_dna_repair <- plotEnrichment(
        hallmark_pathways[[dna_repair_name]],
        ranks
    ) +
        labs(
            title = "GSEA Hallmark: reparación del ADN",
            subtitle = paste0(
                "NES = ", round(dna_repair_result$NES, 2),
                " | FDR = ",
                format(dna_repair_result$padj, scientific = TRUE, digits = 2)
            ),
            x = "Genes ordenados según el estadístico t (IR vs CTL)",
            y = "Puntuación de enriquecimiento"
        ) +
        theme_classic(base_size = 13) +
        theme(
            plot.title = element_text(face = "bold", hjust = 0.5, size = 16),
            plot.subtitle = element_text(hjust = 0.5, size = 12)
        )

    ggsave(
        "figures/GSEA/Hallmark_DNA_repair_enrichment.pdf",
        p_dna_repair,
        width = 8,
        height = 5
    )

    ggsave(
        "figures/GSEA/Hallmark_DNA_repair_enrichment.png",
        p_dna_repair,
        width = 8,
        height = 5,
        dpi = 300
    )
}


# =============================================================================
# 18C. TNFA / NF-KB ENRICHMENT CURVE
# =============================================================================

tnfa_name <- "HALLMARK_TNFA_SIGNALING_VIA_NFKB"

if (tnfa_name %in% names(hallmark_pathways)) {

    tnfa_result <- hallmark_gsea[
        hallmark_gsea$pathway == tnfa_name,
        ,
        drop = FALSE
    ]

    p_tnfa <- plotEnrichment(
        hallmark_pathways[[tnfa_name]],
        ranks
    ) +
        labs(
            title = "Enriquecimiento de la señalización TNFα vía NF-κB",
            subtitle = paste0(
                "NES = ", round(tnfa_result$NES, 2),
                " | FDR = ",
                format(tnfa_result$padj, scientific = TRUE, digits = 2)
            ),
            x = "Posición en el ranking de genes",
            y = "Puntuación de enriquecimiento"
        ) +
        theme_classic(base_size = 13) +
        theme(
            plot.title = element_text(face = "bold")
        )

    ggsave(
        "figures/GSEA/Hallmark_TNFA_NFKB_enrichment.pdf",
        p_tnfa,
        width = 8,
        height = 5
    )

    ggsave(
        "figures/GSEA/Hallmark_TNFA_NFKB_enrichment.png",
        p_tnfa,
        width = 8,
        height = 5,
        dpi = 300
    )
}


# =============================================================================
# 19. REPRESENTATIVE GO:BP FIGURE
# =============================================================================
# Final TFM selection: four representative processes enriched towards IR
# and three representative processes enriched towards CTL.

go_selected <- c(
    "GOBP_ELECTRON_TRANSPORT_CHAIN",
    "GOBP_OXIDATIVE_PHOSPHORYLATION",
    "GOBP_INTRINSIC_APOPTOTIC_SIGNALING_PATHWAY_BY_P53_CLASS_MEDIATOR",
    "GOBP_RESPONSE_TO_OXIDATIVE_STRESS",
    "GOBP_SYNAPSE_ASSEMBLY",
    "GOBP_DENDRITE_DEVELOPMENT",
    "GOBP_REGULATION_OF_TRANS_SYNAPTIC_SIGNALING"
)

go_labels <- c(
    GOBP_ELECTRON_TRANSPORT_CHAIN =
        "Cadena de transporte de electrones",
    GOBP_OXIDATIVE_PHOSPHORYLATION =
        "Fosforilación oxidativa",
    GOBP_INTRINSIC_APOPTOTIC_SIGNALING_PATHWAY_BY_P53_CLASS_MEDIATOR =
        "Apoptosis intrínseca mediada por p53",
    GOBP_RESPONSE_TO_OXIDATIVE_STRESS =
        "Respuesta al estrés oxidativo",
    GOBP_SYNAPSE_ASSEMBLY =
        "Ensamblaje de sinapsis",
    GOBP_DENDRITE_DEVELOPMENT =
        "Desarrollo de dendritas",
    GOBP_REGULATION_OF_TRANS_SYNAPTIC_SIGNALING =
        "Regulación de la señalización transináptica"
)

gobp_plot_df <- gobp_gsea[
    gobp_gsea$pathway %in% go_selected,
    ,
    drop = FALSE
]

missing_go_figure <- setdiff(
    go_selected,
    gobp_plot_df$pathway
)

if (length(missing_go_figure) > 0L) {
    warning(
        "The following GO:BP pathways selected for the TFM figure were not found: ",
        paste(missing_go_figure, collapse = ", ")
    )
}

gobp_plot_df$Proceso <- unname(
    go_labels[gobp_plot_df$pathway]
)

gobp_plot_df$Direccion <- ifelse(
    gobp_plot_df$NES > 0,
    "Enriquecida hacia IR",
    "Enriquecida hacia CTL"
)

gobp_plot_df$Proceso <- factor(
    gobp_plot_df$Proceso,
    levels = gobp_plot_df$Proceso[order(gobp_plot_df$NES)]
)

p_gobp <- ggplot(
    gobp_plot_df,
    aes(
        x = NES,
        y = Proceso,
        fill = Direccion
    )
) +
    geom_col(width = 0.75) +
    geom_vline(
        xintercept = 0,
        linetype = "dashed",
        linewidth = 0.4
    ) +
    scale_fill_manual(
        values = c(
            "Enriquecida hacia CTL" = "#F8766D",
            "Enriquecida hacia IR" = "#00BFC4"
        )
    ) +
    labs(
        title = "Enriquecimiento funcional Gene Ontology",
        subtitle = "GSEA: IR frente a CTL en neuronas inducidas a 336 h",
        x = "NES",
        y = NULL,
        fill = "Dirección"
    ) +
    theme_classic(base_size = 12) +
    theme(
        plot.title = element_text(face = "bold"),
        legend.position = "right"
    )

ggsave(
    "figures/GSEA/GO_BP_representative_NES.pdf",
    p_gobp,
    width = 12,
    height = 5.5
)

ggsave(
    "figures/GSEA/GO_BP_representative_NES.png",
    p_gobp,
    width = 12,
    height = 5.5,
    dpi = 300
)


# =============================================================================
# 20. REPRESENTATIVE KEGG FIGURE
# =============================================================================
# Final TFM selection: five representative pathways enriched towards IR
# and four representative pathways enriched towards CTL.

kegg_selected <- c(
    "KEGG_P53_SIGNALING_PATHWAY",
    "KEGG_OXIDATIVE_PHOSPHORYLATION",
    "KEGG_GLUTATHIONE_METABOLISM",
    "KEGG_CYTOKINE_CYTOKINE_RECEPTOR_INTERACTION",
    "KEGG_APOPTOSIS",
    "KEGG_CALCIUM_SIGNALING_PATHWAY",
    "KEGG_NEUROACTIVE_LIGAND_RECEPTOR_INTERACTION",
    "KEGG_AXON_GUIDANCE",
    "KEGG_LONG_TERM_POTENTIATION"
)

kegg_labels <- c(
    KEGG_P53_SIGNALING_PATHWAY =
        "Señalización de p53",
    KEGG_OXIDATIVE_PHOSPHORYLATION =
        "Fosforilación oxidativa",
    KEGG_GLUTATHIONE_METABOLISM =
        "Metabolismo del glutatión",
    KEGG_CYTOKINE_CYTOKINE_RECEPTOR_INTERACTION =
        "Interacción citocina-receptor",
    KEGG_APOPTOSIS =
        "Apoptosis",
    KEGG_CALCIUM_SIGNALING_PATHWAY =
        "Señalización de calcio",
    KEGG_NEUROACTIVE_LIGAND_RECEPTOR_INTERACTION =
        "Interacción ligando-receptor neuroactivo",
    KEGG_AXON_GUIDANCE =
        "Guía axonal",
    KEGG_LONG_TERM_POTENTIATION =
        "Potenciación a largo plazo"
)

kegg_plot_df <- kegg_gsea[
    kegg_gsea$pathway %in% kegg_selected,
    ,
    drop = FALSE
]

missing_kegg_figure <- setdiff(
    kegg_selected,
    kegg_plot_df$pathway
)

if (length(missing_kegg_figure) > 0L) {
    warning(
        "The following KEGG pathways selected for the TFM figure were not found: ",
        paste(missing_kegg_figure, collapse = ", ")
    )
}

kegg_plot_df$Via <- unname(
    kegg_labels[kegg_plot_df$pathway]
)

kegg_plot_df$Direccion <- ifelse(
    kegg_plot_df$NES > 0,
    "Enriquecida hacia IR",
    "Enriquecida hacia CTL"
)

kegg_plot_df$Via <- factor(
    kegg_plot_df$Via,
    levels = kegg_plot_df$Via[order(kegg_plot_df$NES)]
)

p_kegg <- ggplot(
    kegg_plot_df,
    aes(
        x = NES,
        y = Via,
        fill = Direccion
    )
) +
    geom_col(width = 0.75) +
    geom_vline(
        xintercept = 0,
        linetype = "dashed",
        linewidth = 0.4
    ) +
    scale_fill_manual(
        values = c(
            "Enriquecida hacia CTL" = "#F8766D",
            "Enriquecida hacia IR" = "#00BFC4"
        )
    ) +
    labs(
        title = "Enriquecimiento de vías KEGG",
        subtitle = "GSEA: IR frente a CTL en neuronas inducidas a 336 h",
        x = "NES",
        y = NULL,
        fill = "Dirección"
    ) +
    theme_classic(base_size = 12) +
    theme(
        plot.title = element_text(face = "bold"),
        legend.position = "right"
    )

ggsave(
    "figures/GSEA/KEGG_representative_NES.pdf",
    p_kegg,
    width = 12,
    height = 5.5
)

ggsave(
    "figures/GSEA/KEGG_representative_NES.png",
    p_kegg,
    width = 12,
    height = 5.5,
    dpi = 300
)


# =============================================================================
# 20B. INTEGRATED FUNCTIONAL PROFILE: HALLMARK + GO + KEGG
# =============================================================================
# Final TFM selection. Colour represents enrichment direction, shape represents
# gene-set collection, and point size represents -log10(FDR).

integrated_hallmark <- c(
    HALLMARK_P53_PATHWAY =
        "Vía de p53",
    HALLMARK_TNFA_SIGNALING_VIA_NFKB =
        "TNFα vía NF-κB",
    HALLMARK_DNA_REPAIR =
        "Reparación del ADN"
)

integrated_go <- c(
    GOBP_OXIDATIVE_PHOSPHORYLATION =
        "Fosforilación oxidativa",
    GOBP_INTRINSIC_APOPTOTIC_SIGNALING_PATHWAY_BY_P53_CLASS_MEDIATOR =
        "Apoptosis intrínseca mediada por p53",
    GOBP_RESPONSE_TO_OXIDATIVE_STRESS =
        "Respuesta al estrés oxidativo",
    GOBP_DENDRITE_DEVELOPMENT =
        "Desarrollo de dendritas",
    GOBP_REGULATION_OF_TRANS_SYNAPTIC_SIGNALING =
        "Regulación de la señalización transináptica"
)

integrated_kegg <- c(
    KEGG_GLUTATHIONE_METABOLISM =
        "Metabolismo del glutatión",
    KEGG_CYTOKINE_CYTOKINE_RECEPTOR_INTERACTION =
        "Interacción citocina-receptor",
    KEGG_LONG_TERM_POTENTIATION =
        "Potenciación a largo plazo",
    KEGG_AXON_GUIDANCE =
        "Guía axonal"
)

make_integrated_df <- function(
    gsea_table,
    pathways,
    collection
) {

    out <- gsea_table[
        gsea_table$pathway %in% names(pathways),
        c("pathway", "NES", "padj"),
        drop = FALSE
    ]

    data.frame(
        Proceso = unname(pathways[out$pathway]),
        NES = out$NES,
        FDR = out$padj,
        Coleccion = collection,
        stringsAsFactors = FALSE
    )
}

integrated_hallmark_df <- make_integrated_df(
    hallmark_gsea,
    integrated_hallmark,
    "Hallmark"
)

integrated_go_df <- make_integrated_df(
    gobp_gsea,
    integrated_go,
    "GO"
)

integrated_kegg_df <- make_integrated_df(
    kegg_gsea,
    integrated_kegg,
    "KEGG"
)

funcional <- rbind(
    integrated_hallmark_df,
    integrated_go_df,
    integrated_kegg_df
)

funcional$Direccion <- ifelse(
    funcional$NES > 0,
    "Enriquecida hacia IR",
    "Enriquecida hacia CTL"
)

funcional$Significancia <- -log10(funcional$FDR)

funcional$Proceso <- factor(
    funcional$Proceso,
    levels = funcional$Proceso[order(funcional$NES)]
)

p_integrated <- ggplot(
    funcional,
    aes(
        x = NES,
        y = Proceso,
        color = Direccion,
        shape = Coleccion,
        size = Significancia
    )
) +
    geom_point(alpha = 0.9) +
    geom_vline(
        xintercept = 0,
        linetype = "dashed",
        linewidth = 0.4
    ) +
    scale_color_manual(
        values = c(
            "Enriquecida hacia CTL" = "#F8766D",
            "Enriquecida hacia IR" = "#00BFC4"
        )
    ) +
    scale_shape_manual(
        values = c(
            Hallmark = 17,
            GO = 16,
            KEGG = 15
        )
    ) +
    labs(
        title = "Perfil funcional integrado de la respuesta a IR",
        subtitle = "Hallmark, GO y KEGG en neuronas inducidas a 336 h",
        x = "NES",
        y = NULL,
        color = "Dirección",
        shape = "Colección",
        size = expression(-log[10](FDR))
    ) +
    theme_classic(base_size = 12) +
    theme(
        plot.title = element_text(face = "bold"),
        legend.position = "right"
    )

ggsave(
    "figures/GSEA/integrated_functional_profile.pdf",
    p_integrated,
    width = 12,
    height = 5.5
)

ggsave(
    "figures/GSEA/integrated_functional_profile.png",
    p_integrated,
    width = 12,
    height = 5.5,
    dpi = 300
)


# =============================================================================
# 21. SAVE R OBJECTS
# =============================================================================

saveRDS(
    ranks,
    "results/GSEA/GSEA_ranked_genes.rds"
)

saveRDS(
    hallmark_gsea,
    "results/GSEA/Hallmark_GSEA.rds"
)

saveRDS(
    gobp_gsea,
    "results/GSEA/GO_BP_GSEA.rds"
)

saveRDS(
    kegg_gsea,
    "results/GSEA/KEGG_Legacy_GSEA.rds"
)


# =============================================================================
# 22. FINAL SUMMARY
# =============================================================================

cat("\n")
cat("============================================================\n")
cat("TFM GSEA SUMMARY\n")
cat("============================================================\n\n")


cat(
    "Genes in ranked list:",
    length(ranks),
    "\n\n"
)


cat("HALLMARK\n")

cat(
    "  Tested:",
    nrow(hallmark_gsea),
    "\n"
)

cat(
    "  Significant:",
    nrow(hallmark_sig),
    "\n"
)

cat(
    "  Positive / IR:",
    sum(hallmark_sig$NES > 0),
    "\n"
)

cat(
    "  Negative / CTL:",
    sum(hallmark_sig$NES < 0),
    "\n\n"
)


cat("GO:BP\n")

cat(
    "  Tested:",
    nrow(gobp_gsea),
    "\n"
)

cat(
    "  Significant:",
    nrow(gobp_sig),
    "\n"
)

cat(
    "  Positive / IR:",
    nrow(gobp_positive),
    "\n"
)

cat(
    "  Negative / CTL:",
    nrow(gobp_negative),
    "\n\n"
)


cat("KEGG LEGACY\n")

cat(
    "  Tested:",
    nrow(kegg_gsea),
    "\n"
)

cat(
    "  Significant:",
    nrow(kegg_sig),
    "\n"
)

cat(
    "  Positive / IR:",
    nrow(kegg_positive),
    "\n"
)

cat(
    "  Negative / CTL:",
    nrow(kegg_negative),
    "\n\n"
)


cat("Selected Hallmark pathways:\n")

print(
    hallmark_interest[
        ,
        c(
            "pathway",
            "size",
            "ES",
            "NES",
            "padj"
        )
    ],
    row.names = FALSE
)


cat("\nLeading-edge sizes:\n")

print(
    hallmark_leading_edge_table[
        ,
        c(
            "pathway",
            "leading_edge_n"
        )
    ],
    row.names = FALSE
)


cat("\nLeading-edge overlap:\n")

print(
    leading_edge_overlap[
        ,
        c(
            "comparison",
            "shared_genes_n"
        )
    ],
    row.names = FALSE
)


# =============================================================================
# 23. REPRODUCIBILITY CHECKPOINTS
# =============================================================================

expected_ranked_genes <- 17919L
expected_hallmark <- 50L
expected_gobp <- 3825L
expected_kegg <- 165L


cat("\nExpected reproducibility checkpoints:\n")

cat(
    "  Ranked genes:              17,919\n"
)

cat(
    "  Hallmark tested:               50\n"
)

cat(
    "  GO:BP terms evaluated:      3,825\n"
)

cat(
    "  KEGG pathways evaluated:      165\n"
)

cat(
    "  Hallmark p53 NES:           ~3.25\n"
)

cat(
    "  Hallmark DNA repair NES:    ~2.34\n"
)

cat(
    "  Hallmark G2/M NES:         ~-2.09\n"
)


if (length(ranks) != expected_ranked_genes) {

    warning(
        "Ranked gene count differs from expected value: ",
        length(ranks),
        " vs 17,919."
    )
}


if (nrow(hallmark_gsea) != expected_hallmark) {

    warning(
        "Hallmark pathway count differs from expected value: ",
        nrow(hallmark_gsea),
        " vs 50."
    )
}


if (nrow(gobp_gsea) != expected_gobp) {

    warning(
        "GO:BP term count differs from expected value: ",
        nrow(gobp_gsea),
        " vs 3,825. Check MSigDB/msigdbr version."
    )
}


if (nrow(kegg_gsea) != expected_kegg) {

    warning(
        "KEGG pathway count differs from expected value: ",
        nrow(kegg_gsea),
        " vs 165. Check MSigDB/msigdbr version."
    )
}


# =============================================================================
# 24. CHECK KEY HALLMARK NES VALUES
# =============================================================================

get_nes <- function(pathway_name) {

    value <- hallmark_gsea$NES[
        hallmark_gsea$pathway ==
            pathway_name
    ]

    if (length(value) != 1L) {
        return(NA_real_)
    }

    value
}


p53_nes <- get_nes(
    "HALLMARK_P53_PATHWAY"
)

dna_repair_nes <- get_nes(
    "HALLMARK_DNA_REPAIR"
)

g2m_nes <- get_nes(
    "HALLMARK_G2M_CHECKPOINT"
)


if (
    !is.na(p53_nes) &&
    abs(p53_nes - 3.25) > 0.05
) {

    warning(
        "P53 pathway NES differs from expected value: ",
        round(p53_nes, 3)
    )
}


if (
    !is.na(dna_repair_nes) &&
    abs(dna_repair_nes - 2.34) > 0.05
) {

    warning(
        "DNA repair NES differs from expected value: ",
        round(dna_repair_nes, 3)
    )
}


if (
    !is.na(g2m_nes) &&
    abs(g2m_nes - (-2.09)) > 0.05
) {

    warning(
        "G2/M checkpoint NES differs from expected value: ",
        round(g2m_nes, 3)
    )
}


# =============================================================================
# 25. SESSION INFORMATION
# =============================================================================

capture.output(
    sessionInfo(),
    file = "results/GSEA/sessionInfo_GSEA.txt"
)


# =============================================================================
# 26. COMPLETE
# =============================================================================

cat("\nFiles generated under:\n")
cat("  results/GSEA/\n")
cat("  figures/GSEA/\n")


cat("\n============================================================\n")
cat("04 GSEA COMPLETE\n")
cat("============================================================\n")