# =============================================================================
# 07_sensitivity_34_libraries.R
#
# TFM - Analysis of the 34-library subset (17 CTL + 17 IR)
#
# Purpose:
#   Re-run the 34-library analysis from the original count matrix rather than
#   reading "resultados_sensibilidad_34_bibliotecas.csv".
#
# Expected historical checkpoints:
#   34 libraries (17 CTL + 17 IR)
#   17 donors
#   21,713 genes after filterByExpr()
#
# Required inputs generated by 01_data_preparation.R:
#   data/processed/count_matrix_54.rds
#   data/processed/sample_metadata_54.csv
#
# Optional historical selection file:
#   seleccion_17_donantes_34_bibliotecas.csv
# If it is present, the script uses it. Otherwise, the donor-batch selection
# recovered from the project history is used.
# =============================================================================


# =============================================================================
# 1. PACKAGES
# =============================================================================

required <- c("edgeR", "limma")

missing_pkgs <- required[
    !vapply(required, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_pkgs) > 0L) {
    stop(
        "Install missing packages before running this script: ",
        paste(missing_pkgs, collapse = ", ")
    )
}

library(edgeR)
library(limma)


# =============================================================================
# 2. INPUTS
# =============================================================================

counts_file <- "data/processed/count_matrix_54.rds"
meta_file   <- "data/processed/sample_metadata_54.csv"
selection_file <- "seleccion_17_donantes_34_bibliotecas.csv"

if (!file.exists(counts_file)) {
    stop(
        "Missing ", counts_file,
        ". Run 01_data_preparation.R first."
    )
}

if (!file.exists(meta_file)) {
    stop(
        "Missing ", meta_file,
        ". Run 01_data_preparation.R first."
    )
}

counts54 <- readRDS(counts_file)

meta54 <- read.csv(
    meta_file,
    stringsAsFactors = FALSE,
    check.names = FALSE
)

required_meta <- c(
    "GSM",
    "donor",
    "batch",
    "treatment",
    "count_column"
)

if (!all(required_meta %in% names(meta54))) {
    stop(
        "Missing metadata columns: ",
        paste(
            setdiff(required_meta, names(meta54)),
            collapse = ", "
        )
    )
}

if (ncol(counts54) != 54L || nrow(meta54) != 54L) {
    stop(
        "The processed input does not contain the expected 54 libraries."
    )
}

if (!all(meta54$count_column %in% colnames(counts54))) {
    stop(
        "The count_column values in metadata do not match count-matrix columns."
    )
}


# =============================================================================
# 3. HISTORICAL 17 DONOR-BATCH PAIRS
# =============================================================================
#
# The 34-library analysis contains one CTL/IR donor-batch pair for each donor.
# Prefer the historical CSV when available.
# =============================================================================

if (file.exists(selection_file)) {

    sel_raw <- read.csv(
        selection_file,
        stringsAsFactors = FALSE,
        check.names = FALSE
    )

    # Accept common historical column names.
    donor_col <- intersect(
        c("donor", "Donor", "donor_id", "Donor_ID"),
        names(sel_raw)
    )

    batch_col <- intersect(
        c("batch", "Batch", "batch_id", "Batch_ID"),
        names(sel_raw)
    )

    if (length(donor_col) == 0L || length(batch_col) == 0L) {
        stop(
            selection_file,
            " exists, but donor/batch columns could not be identified."
        )
    }

    sel34 <- unique(
        data.frame(
            donor = as.character(sel_raw[[donor_col[1]]]),
            batch = as.character(sel_raw[[batch_col[1]]]),
            stringsAsFactors = FALSE
        )
    )

} else {

    # Selection recovered from the historical project material.
    sel34 <- data.frame(
        donor = c(
            "A18", "A27", "A31", "A37", "A48",
            "ID11", "ID20", "ID32", "ID37", "ID48",
            "ID53", "ID6", "ID66", "ID73", "ID91",
            "ID97", "ID98"
        ),
        batch = c(
            "J086_Batch_1",
            "J080_Batch_1",
            "J080_Batch_1",
            "J080_Batch_1",
            "J080_Batch_1",
            "J082_4_Batch_1",
            "J085DR_Batch_2",
            "J085DR_Batch_2",
            "J084_2_Batch_1",
            "J080_Batch_1",
            "J085DR_Batch_2",
            "J084_2_Batch_1",
            "J085DR_Batch_2",
            "J084_1_Batch_1",
            "J082_4_Batch_1",
            "J086_Batch_1",
            "J085_Batch_1"
        ),
        stringsAsFactors = FALSE
    )
}

if (nrow(sel34) != 17L) {
    stop(
        "The historical selection must contain exactly 17 donor-batch pairs; ",
        "found ", nrow(sel34), "."
    )
}


# =============================================================================
# 4. SELECT THE 34 LIBRARIES
# =============================================================================

meta54$pair_key <- paste(
    meta54$donor,
    meta54$batch,
    sep = "___"
)

sel34$pair_key <- paste(
    sel34$donor,
    sel34$batch,
    sep = "___"
)

meta34 <- meta54[
    meta54$pair_key %in% sel34$pair_key,
    ,
    drop = FALSE
]

# Keep the historical donor order and CTL before IR.
meta34$donor_order <- match(
    meta34$donor,
    sel34$donor
)

meta34$treatment <- factor(
    meta34$treatment,
    levels = c("CTL", "IR")
)

meta34 <- meta34[
    order(meta34$donor_order, meta34$treatment),
    ,
    drop = FALSE
]

rownames(meta34) <- NULL

pair_table <- table(
    paste(meta34$donor, meta34$batch, sep = "___"),
    meta34$treatment
)

cat("\n============================================================\n")
cat("34-LIBRARY SUBSET\n")
cat("============================================================\n")
cat("Libraries:", nrow(meta34), "\n")
cat("Donors:", length(unique(meta34$donor)), "\n")
cat("Donor-batch pairs:", nrow(pair_table), "\n")
print(table(meta34$treatment))

stopifnot(
    nrow(meta34) == 34L,
    length(unique(meta34$donor)) == 17L,
    nrow(pair_table) == 17L,
    all(pair_table[, "CTL"] == 1L),
    all(pair_table[, "IR"] == 1L)
)

counts34 <- counts54[
    ,
    meta34$count_column,
    drop = FALSE
]

stopifnot(ncol(counts34) == 34L)


# =============================================================================
# 5. FACTORS AND PAIRED DESIGN
# =============================================================================

meta34$donor <- factor(
    meta34$donor,
    levels = sel34$donor
)

meta34$treatment <- factor(
    meta34$treatment,
    levels = c("CTL", "IR")
)

# With one CTL/IR pair per donor, donor is the blocking factor.
design34 <- model.matrix(
    ~ donor + treatment,
    data = meta34
)

if (qr(design34)$rank != ncol(design34)) {
    stop("The 34-library design matrix is not full rank.")
}


# =============================================================================
# 6. LOW-EXPRESSION FILTERING
# =============================================================================

dge34 <- DGEList(
    counts = counts34,
    samples = meta34
)

keep34 <- filterByExpr(
    dge34,
    design = design34
)

dge34 <- dge34[
    keep34,
    ,
    keep.lib.sizes = FALSE
]

cat("\n============================================================\n")
cat("FILTERING CHECKPOINT\n")
cat("============================================================\n")
cat("Initial genes:", nrow(counts34), "\n")
cat("Genes after filterByExpr:", nrow(dge34), "\n")

if (nrow(dge34) != 21713L) {
    stop(
        "Historical checkpoint not reproduced: expected 21,713 genes, got ",
        nrow(dge34),
        ". Do not continue until the sample selection/filtering is checked."
    )
}

cat("*** HISTORICAL CHECKPOINT REPRODUCED: 21,713 GENES ***\n")


# =============================================================================
# 7. TMM NORMALIZATION
# =============================================================================

dge34 <- calcNormFactors(
    dge34,
    method = "TMM"
)


# =============================================================================
# 8. VOOM + LIMMA
# =============================================================================

v34 <- voom(
    dge34,
    design34,
    plot = FALSE
)

fit34 <- lmFit(
    v34,
    design34
)

fit34 <- eBayes(fit34)

coef_name <- "treatmentIR"

if (!coef_name %in% colnames(fit34$coefficients)) {
    stop(
        "Could not find treatmentIR in the fitted model. Available coefficients: ",
        paste(colnames(fit34$coefficients), collapse = ", ")
    )
}


# =============================================================================
# 9. DIFFERENTIAL-EXPRESSION RESULTS
# =============================================================================

res34 <- topTable(
    fit34,
    coef = coef_name,
    number = Inf,
    adjust.method = "BH",
    sort.by = "P"
)

sig34_fdr <- res34[
    !is.na(res34$adj.P.Val) &
        res34$adj.P.Val < 0.05,
    ,
    drop = FALSE
]

deg34 <- res34[
    !is.na(res34$adj.P.Val) &
        res34$adj.P.Val < 0.05 &
        abs(res34$logFC) >= 1,
    ,
    drop = FALSE
]

cat("\n============================================================\n")
cat("34-LIBRARY RESULTS\n")
cat("============================================================\n")
cat("Genes evaluated:", nrow(res34), "\n")
cat("FDR < 0.05:", nrow(sig34_fdr), "\n")
cat("FDR < 0.05 and |log2FC| >= 1:", nrow(deg34), "\n")
cat("Higher in IR:", sum(deg34$logFC >= 1), "\n")
cat("Lower in IR:", sum(deg34$logFC <= -1), "\n")


# =============================================================================
# 10. HISTORICAL RESULT CHECKPOINTS
# =============================================================================

expected_fdr <- 6389L
expected_deg <- 467L

if (nrow(sig34_fdr) != expected_fdr) {
    warning(
        "Historical FDR checkpoint differs: expected ",
        expected_fdr,
        ", obtained ",
        nrow(sig34_fdr),
        "."
    )
}

if (nrow(deg34) != expected_deg) {
    warning(
        "Historical DEG checkpoint differs: expected ",
        expected_deg,
        ", obtained ",
        nrow(deg34),
        "."
    )
}


# =============================================================================
# 11. SAVE REGENERATED OUTPUTS
# =============================================================================

out_dir <- "results/sensitivity_34_libraries"

dir.create(
    out_dir,
    recursive = TRUE,
    showWarnings = FALSE
)

write.csv(
    meta34[
        ,
        setdiff(names(meta34), c("pair_key", "donor_order")),
        drop = FALSE
    ],
    file.path(out_dir, "selected_34_libraries.csv"),
    row.names = FALSE
)

write.csv(
    res34,
    file.path(out_dir, "resultados_sensibilidad_34_bibliotecas.csv"),
    row.names = TRUE
)

write.csv(
    sig34_fdr,
    file.path(out_dir, "genes_FDR_0.05_34_bibliotecas.csv"),
    row.names = TRUE
)

write.csv(
    deg34,
    file.path(out_dir, "DEGs_FDR_0.05_abslogFC1_34_bibliotecas.csv"),
    row.names = TRUE
)

saveRDS(
    dge34,
    file.path(out_dir, "dge_34_bibliotecas.rds")
)

capture.output(
    sessionInfo(),
    file = file.path(out_dir, "sessionInfo_34_bibliotecas.txt")
)

cat("\nFiles written to:", out_dir, "\n")
cat("Analysis complete.\n")
